AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] #as per VGG 16 model
BATCH_SIZE: 16 # IF YOU HAVE A GOOD MACHINE YOU CAN INCREASE IT
INCLUDE_TOP: False # WE WANT TO TRAIN MY CUSTOM LAYER ONLY
EPOCHS: 2 # YOU CAN INCREASE IT HERE WE ARE JUST LEARNING
CLASSES: 2 # AS WE HAVE 2 CLASSES (COCCIDILE AND HEALTHY)
WEIGHTS: imagenet
LEARNING_RATE: 0.01